/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dedhi
 */
public class CreateJPanel extends javax.swing.JPanel {
    //create reference of product object
    Product product;
    String productImagePath;
    /**
     * Creates new form CreateJForm
     */
    public CreateJPanel(Product product) {
        //initialize the product object to reference passed in the constructor
        this.product = product;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBrandNameLabel = new javax.swing.JLabel();
        jModelNameLabel = new javax.swing.JLabel();
        jModelNumberLabel = new javax.swing.JLabel();
        jSerialNumberLabel = new javax.swing.JLabel();
        jColorLabel = new javax.swing.JLabel();
        jEngineTypeLabel = new javax.swing.JLabel();
        jHorsePowerLabel = new javax.swing.JLabel();
        jFuelEconomyLabel = new javax.swing.JLabel();
        jFuelTankCapacityLabel = new javax.swing.JLabel();
        jBodyMaterialLabel = new javax.swing.JLabel();
        jMaxSpeedLabel = new javax.swing.JLabel();
        jBrakeTypeLabel = new javax.swing.JLabel();
        jBootSpaceLabel = new javax.swing.JLabel();
        jTowingCapacityLabel = new javax.swing.JLabel();
        jTorqueLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCreateBtn = new javax.swing.JButton();
        jBrandNameTxtField = new javax.swing.JTextField();
        jModelNameTxtField = new javax.swing.JTextField();
        jSerialNumberTxtField = new javax.swing.JTextField();
        jColorTxtField = new javax.swing.JTextField();
        jBodyMaterialTxtField = new javax.swing.JTextField();
        jEngineTypeTxtField = new javax.swing.JTextField();
        jTowingCapacityTxtField = new javax.swing.JTextField();
        jModelNumberTxtField = new javax.swing.JTextField();
        jMaxSpeedTxtField = new javax.swing.JTextField();
        jBootSpaceTxtField = new javax.swing.JTextField();
        jTorqueTxtField = new javax.swing.JTextField();
        jBrakeTypeTxtField = new javax.swing.JTextField();
        jHorsePowerTxtField = new javax.swing.JTextField();
        jFuelTankCapTxtField = new javax.swing.JTextField();
        jFuelEconomyTxtField = new javax.swing.JTextField();
        jProductImagePathBtn = new javax.swing.JButton();
        jProductImagePathLabel = new javax.swing.JLabel();

        jBrandNameLabel.setText("Brand Name:");

        jModelNameLabel.setText("Model Name:");

        jModelNumberLabel.setText("Model Number:");

        jSerialNumberLabel.setText("Serial Number:");

        jColorLabel.setText("Color:");

        jEngineTypeLabel.setText("Engine Type:");

        jHorsePowerLabel.setText("Horse Power:");

        jFuelEconomyLabel.setText("Fuel Economy:");

        jFuelTankCapacityLabel.setText("Fuel Tank Capacity:");

        jBodyMaterialLabel.setText("Body Material:");

        jMaxSpeedLabel.setText("Max Speed:");

        jBrakeTypeLabel.setText("Brake Type:");

        jBootSpaceLabel.setText("Boot Space:");

        jTowingCapacityLabel.setText("Towing Capacity:");

        jTorqueLabel.setText("Torque:");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel16.setText("Create your Car");

        jCreateBtn.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jCreateBtn.setText("Create");
        jCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateBtnActionPerformed(evt);
            }
        });

        jProductImagePathBtn.setText("Upload Image");
        jProductImagePathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductImagePathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jHorsePowerLabel)
                                    .addComponent(jEngineTypeLabel)
                                    .addComponent(jColorLabel)
                                    .addComponent(jSerialNumberLabel)
                                    .addComponent(jModelNumberLabel)
                                    .addComponent(jModelNameLabel)
                                    .addComponent(jBrandNameLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTowingCapacityLabel)
                                    .addComponent(jBrakeTypeLabel)
                                    .addComponent(jBootSpaceLabel)
                                    .addComponent(jMaxSpeedLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTorqueLabel)
                                        .addGap(8, 8, 8))))
                            .addComponent(jFuelEconomyLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFuelTankCapacityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBodyMaterialLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTorqueTxtField)
                            .addComponent(jBrandNameTxtField)
                            .addComponent(jModelNameTxtField)
                            .addComponent(jModelNumberTxtField)
                            .addComponent(jSerialNumberTxtField)
                            .addComponent(jColorTxtField)
                            .addComponent(jEngineTypeTxtField)
                            .addComponent(jHorsePowerTxtField)
                            .addComponent(jFuelTankCapTxtField)
                            .addComponent(jBodyMaterialTxtField)
                            .addComponent(jFuelEconomyTxtField)
                            .addComponent(jMaxSpeedTxtField)
                            .addComponent(jBootSpaceTxtField)
                            .addComponent(jBrakeTypeTxtField)
                            .addComponent(jTowingCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jProductImagePathBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProductImagePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel16)))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrandNameLabel)
                    .addComponent(jBrandNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModelNameLabel)
                    .addComponent(jModelNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModelNumberLabel)
                    .addComponent(jModelNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSerialNumberLabel)
                    .addComponent(jSerialNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jColorLabel)
                    .addComponent(jColorTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEngineTypeLabel)
                    .addComponent(jEngineTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHorsePowerLabel)
                    .addComponent(jHorsePowerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFuelEconomyLabel)
                    .addComponent(jFuelEconomyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFuelTankCapTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFuelTankCapacityLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBodyMaterialTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBodyMaterialLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMaxSpeedLabel)
                    .addComponent(jMaxSpeedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBootSpaceLabel)
                    .addComponent(jBootSpaceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrakeTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrakeTypeLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTorqueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTorqueLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTowingCapacityLabel)
                    .addComponent(jTowingCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProductImagePathBtn)
                    .addComponent(jProductImagePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateBtnActionPerformed
        // TODO add your handling code here:
        //sets the value of product object as per given by the user in respective text fields
        product.setBrandName(jBrandNameTxtField.getText());
        product.setModelName(jModelNameTxtField.getText());
        product.setModelNumber(jModelNumberTxtField.getText());
        product.setSerialNumber(jSerialNumberTxtField.getText());
        product.setColor(jColorTxtField.getText());
        product.setEngineType(jEngineTypeTxtField.getText());
        product.setHorsePower(jHorsePowerTxtField.getText());
        product.setFuelEconomy(jFuelEconomyTxtField.getText());
        product.setFuelTankCapacity(jFuelTankCapTxtField.getText());
        product.setBodyMaterial(jBodyMaterialTxtField.getText());
        product.setMaxSpeed(jMaxSpeedTxtField.getText());
        product.setBootSpace(jBootSpaceTxtField.getText());
        product.setBrakeType(jBrakeTypeTxtField.getText());
        product.setTorque(jTorqueTxtField.getText());
        product.setTowingCapacity(jTowingCapacityTxtField.getText());
        product.setProductImagePath(productImagePath); 
        
        //shows a message box saying product created successfully
        JOptionPane.showMessageDialog(null,"Car created successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jCreateBtnActionPerformed

    private void jProductImagePathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductImagePathBtnActionPerformed
        // TODO add your handling code here:
        //selects the image and sets its path in product object varibale
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select an image of your Car");
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter nameFilter = new FileNameExtensionFilter("PNG, JPG and JPEG files only","png","jpg","jpeg");
        fileChooser.addChoosableFileFilter(nameFilter);
        int i = fileChooser.showOpenDialog(fileChooser);
        
        if(i == JFileChooser.APPROVE_OPTION)
        {
            productImagePath = fileChooser.getSelectedFile().getAbsolutePath();
            jProductImagePathLabel.setText(fileChooser.getSelectedFile().getName());
                
        }else {
            JOptionPane.showMessageDialog(null,"No file selected","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jProductImagePathBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBodyMaterialLabel;
    private javax.swing.JTextField jBodyMaterialTxtField;
    private javax.swing.JLabel jBootSpaceLabel;
    private javax.swing.JTextField jBootSpaceTxtField;
    private javax.swing.JLabel jBrakeTypeLabel;
    private javax.swing.JTextField jBrakeTypeTxtField;
    private javax.swing.JLabel jBrandNameLabel;
    private javax.swing.JTextField jBrandNameTxtField;
    private javax.swing.JLabel jColorLabel;
    private javax.swing.JTextField jColorTxtField;
    private javax.swing.JButton jCreateBtn;
    private javax.swing.JLabel jEngineTypeLabel;
    private javax.swing.JTextField jEngineTypeTxtField;
    private javax.swing.JLabel jFuelEconomyLabel;
    private javax.swing.JTextField jFuelEconomyTxtField;
    private javax.swing.JTextField jFuelTankCapTxtField;
    private javax.swing.JLabel jFuelTankCapacityLabel;
    private javax.swing.JLabel jHorsePowerLabel;
    private javax.swing.JTextField jHorsePowerTxtField;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jMaxSpeedLabel;
    private javax.swing.JTextField jMaxSpeedTxtField;
    private javax.swing.JLabel jModelNameLabel;
    private javax.swing.JTextField jModelNameTxtField;
    private javax.swing.JLabel jModelNumberLabel;
    private javax.swing.JTextField jModelNumberTxtField;
    private javax.swing.JButton jProductImagePathBtn;
    private javax.swing.JLabel jProductImagePathLabel;
    private javax.swing.JLabel jSerialNumberLabel;
    private javax.swing.JTextField jSerialNumberTxtField;
    private javax.swing.JLabel jTorqueLabel;
    private javax.swing.JTextField jTorqueTxtField;
    private javax.swing.JLabel jTowingCapacityLabel;
    private javax.swing.JTextField jTowingCapacityTxtField;
    // End of variables declaration//GEN-END:variables
}
