/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author dedhi
 */
public class ViewJPanel extends javax.swing.JPanel {
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Product product) {
        initComponents();
    
        //disable the text box as users can't change the text during view
       /* jBrandNameTxtField.setEnabled(false);
        jModelNameTxtField.setEnabled(false);
        jModelNumberTxtField.setEnabled(false);
        jSerialNumberTxtField.setEnabled(false);
        jColorTxtField.setEnabled(false);
        jEngineTypeTxtField.setEnabled(false);
        jHorsePowerTxtField.setEnabled(false);
        jFuelEconomyTxtField.setEnabled(false);
        jFuelTankCapTxtField.setEnabled(false);
        jBodyMaterialTxtField.setEnabled(false);
        jMaxSpeedTxtField.setEnabled(false);
        jBootSpaceTxtField.setEnabled(false);
        jBrakeTypeTxtField.setEnabled(false);
        jTorqueTxtField.setEnabled(false);
        jTowingCapacityTxtField.setEnabled(false);*/
                
        //gets value of variables of product object and sets it in respective text field
        jProductImageLabel.setSize(550,500);
        jBrandNameTxtField.setText(product.getBrandName());
        jModelNameTxtField.setText(product.getModelName());
        jModelNumberTxtField.setText(product.getModelNumber());
        jSerialNumberTxtField.setText(product.getSerialNumber());
        jColorTxtField.setText(product.getColor());
        jEngineTypeTxtField.setText(product.getEngineType());
        jHorsePowerTxtField.setText(product.getHorsePower());
        jFuelEconomyTxtField.setText(product.getFuelEconomy());
        jFuelTankCapTxtField.setText(product.getFuelTankCapacity());
        jBodyMaterialTxtField.setText(product.getBodyMaterial());
        jMaxSpeedTxtField.setText(product.getMaxSpeed());
        jBootSpaceTxtField.setText(product.getBootSpace());
        jBrakeTypeTxtField.setText(product.getBrakeType());
        jTorqueTxtField.setText(product.getTorque());
        jTowingCapacityTxtField.setText(product.getTowingCapacity());
        
       /* Image i = product.getProductImagePath().getImage();
        Image image = new ImageIcon(product.getProductImagePath()).getImage();
        ImageIcon img = new ImageIcon(image.getScaledInstance(jProductImageLabel.getWidth(), jProductImageLabel.getHeight(),
        Image.SCALE_SMOOTH));
        //jProductImageLabel.setText(product.getProductImagePath());
        jProductImageLabel.setIcon(img);*/
       
       //sets Image in jLabel as per the size of jLabel and path given by user
       Image img = new ImageIcon(product.getProductImagePath()).getImage();
       jProductImageLabel.setIcon(new ImageIcon(img.getScaledInstance(jProductImageLabel.getWidth(), jProductImageLabel.getHeight(),
        Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProductImageLabel = new javax.swing.JLabel();
        jModelNameLabel = new javax.swing.JLabel();
        jTowingCapacityTxtField = new javax.swing.JTextField();
        jModelNumberLabel = new javax.swing.JLabel();
        jModelNumberTxtField = new javax.swing.JTextField();
        jSerialNumberLabel = new javax.swing.JLabel();
        jMaxSpeedTxtField = new javax.swing.JTextField();
        jColorLabel = new javax.swing.JLabel();
        jBootSpaceTxtField = new javax.swing.JTextField();
        jEngineTypeLabel = new javax.swing.JLabel();
        jHorsePowerLabel = new javax.swing.JLabel();
        jTorqueTxtField = new javax.swing.JTextField();
        jBrakeTypeTxtField = new javax.swing.JTextField();
        jFuelEconomyLabel = new javax.swing.JLabel();
        jHorsePowerTxtField = new javax.swing.JTextField();
        jFuelTankCapacityLabel = new javax.swing.JLabel();
        jFuelTankCapTxtField = new javax.swing.JTextField();
        jBodyMaterialLabel = new javax.swing.JLabel();
        jFuelEconomyTxtField = new javax.swing.JTextField();
        jMaxSpeedLabel = new javax.swing.JLabel();
        jBrakeTypeLabel = new javax.swing.JLabel();
        jBootSpaceLabel = new javax.swing.JLabel();
        jTowingCapacityLabel = new javax.swing.JLabel();
        jTorqueLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jBrandNameTxtField = new javax.swing.JTextField();
        jModelNameTxtField = new javax.swing.JTextField();
        jSerialNumberTxtField = new javax.swing.JTextField();
        jColorTxtField = new javax.swing.JTextField();
        jBodyMaterialTxtField = new javax.swing.JTextField();
        jBrandNameLabel = new javax.swing.JLabel();
        jEngineTypeTxtField = new javax.swing.JTextField();

        jModelNameLabel.setText("Model Name:");

        jModelNumberLabel.setText("Model Number:");

        jSerialNumberLabel.setText("Serial Number:");

        jColorLabel.setText("Color:");

        jEngineTypeLabel.setText("Engine Type:");

        jHorsePowerLabel.setText("Horse Power:");

        jFuelEconomyLabel.setText("Fuel Economy:");

        jFuelTankCapacityLabel.setText("Fuel Tank Capacity:");

        jBodyMaterialLabel.setText("Body Material:");

        jMaxSpeedLabel.setText("Max Speed:");

        jBrakeTypeLabel.setText("Brake Type:");

        jBootSpaceLabel.setText("Boot Space:");

        jTowingCapacityLabel.setText("Towing Capacity:");

        jTorqueLabel.setText("Torque:");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel16.setText("View your Car");

        jBrandNameLabel.setText("Brand Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jHorsePowerLabel)
                                        .addComponent(jColorLabel)
                                        .addComponent(jSerialNumberLabel)
                                        .addComponent(jModelNumberLabel)
                                        .addComponent(jModelNameLabel)
                                        .addComponent(jBrandNameLabel)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTowingCapacityLabel)
                                        .addComponent(jTorqueLabel)
                                        .addComponent(jBrakeTypeLabel)
                                        .addComponent(jBootSpaceLabel)
                                        .addComponent(jMaxSpeedLabel)
                                        .addComponent(jBodyMaterialLabel)))
                                .addComponent(jFuelEconomyLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFuelTankCapacityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jEngineTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTorqueTxtField)
                            .addComponent(jBrandNameTxtField)
                            .addComponent(jModelNameTxtField)
                            .addComponent(jModelNumberTxtField)
                            .addComponent(jSerialNumberTxtField)
                            .addComponent(jColorTxtField)
                            .addComponent(jEngineTypeTxtField)
                            .addComponent(jHorsePowerTxtField)
                            .addComponent(jFuelTankCapTxtField)
                            .addComponent(jBodyMaterialTxtField)
                            .addComponent(jFuelEconomyTxtField)
                            .addComponent(jMaxSpeedTxtField)
                            .addComponent(jBootSpaceTxtField)
                            .addComponent(jBrakeTypeTxtField)
                            .addComponent(jTowingCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProductImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBrandNameLabel)
                            .addComponent(jBrandNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jModelNameLabel)
                            .addComponent(jModelNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jModelNumberLabel)
                            .addComponent(jModelNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSerialNumberLabel)
                            .addComponent(jSerialNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jColorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jColorLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEngineTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEngineTypeLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHorsePowerLabel)
                            .addComponent(jHorsePowerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFuelEconomyLabel)
                            .addComponent(jFuelEconomyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFuelTankCapTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFuelTankCapacityLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBodyMaterialTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBodyMaterialLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMaxSpeedLabel)
                            .addComponent(jMaxSpeedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBootSpaceLabel)
                            .addComponent(jBootSpaceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBrakeTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBrakeTypeLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTorqueTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTorqueLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTowingCapacityLabel)
                            .addComponent(jTowingCapacityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jProductImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBodyMaterialLabel;
    private javax.swing.JTextField jBodyMaterialTxtField;
    private javax.swing.JLabel jBootSpaceLabel;
    private javax.swing.JTextField jBootSpaceTxtField;
    private javax.swing.JLabel jBrakeTypeLabel;
    private javax.swing.JTextField jBrakeTypeTxtField;
    private javax.swing.JLabel jBrandNameLabel;
    private javax.swing.JTextField jBrandNameTxtField;
    private javax.swing.JLabel jColorLabel;
    private javax.swing.JTextField jColorTxtField;
    private javax.swing.JLabel jEngineTypeLabel;
    private javax.swing.JTextField jEngineTypeTxtField;
    private javax.swing.JLabel jFuelEconomyLabel;
    private javax.swing.JTextField jFuelEconomyTxtField;
    private javax.swing.JTextField jFuelTankCapTxtField;
    private javax.swing.JLabel jFuelTankCapacityLabel;
    private javax.swing.JLabel jHorsePowerLabel;
    private javax.swing.JTextField jHorsePowerTxtField;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jMaxSpeedLabel;
    private javax.swing.JTextField jMaxSpeedTxtField;
    private javax.swing.JLabel jModelNameLabel;
    private javax.swing.JTextField jModelNameTxtField;
    private javax.swing.JLabel jModelNumberLabel;
    private javax.swing.JTextField jModelNumberTxtField;
    private javax.swing.JLabel jProductImageLabel;
    private javax.swing.JLabel jSerialNumberLabel;
    private javax.swing.JTextField jSerialNumberTxtField;
    private javax.swing.JLabel jTorqueLabel;
    private javax.swing.JTextField jTorqueTxtField;
    private javax.swing.JLabel jTowingCapacityLabel;
    private javax.swing.JTextField jTowingCapacityTxtField;
    // End of variables declaration//GEN-END:variables
}
