/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dedhi
 */
public class CarManufacturerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarManufacturerJPanel
     */
    private JPanel jPanelBottom;
    private CarCatalog carCatalog;
    ArrayList<String> manufacturerArr = new ArrayList<String>();
    ArrayList<String> brandArr = new ArrayList<String>();
    public CarManufacturerJPanel(JPanel jPanelBottom, CarCatalog carCatalog) {
        initComponents();
        this.jPanelBottom = jPanelBottom;
        this.carCatalog = carCatalog;
        populateCarManufacturers();
    }

    public void populateCarManufacturers(){
       int i = 1;
       for(Car c: carCatalog.getCarCatalog())
       {
           if(!manufacturerArr.contains(c.getManufacturerName()))
           {
               manufacturerArr.add(c.getManufacturerName());
               JCheckBox cb = new JCheckBox();
               cb.setSelected(true);
               cb.setLocation(5,i*20);
               cb.setSize(200,30);
               cb.setText(c.getManufacturerName());
               jPanelCarManufacturer.add(cb);
               cb.setName(c.getManufacturerName()+i);
               i++; 
           }  
       }
    }
    
    public void populateCarBrand(){
       int i = 1;
       for(Car c: carCatalog.getCarCatalog())
       {
           if((!brandArr.contains(c.getBrand())) && (manufacturerArr.contains(c.getManufacturerName())))
           {
               brandArr.add(c.getBrand());
               JCheckBox cb = new JCheckBox();
               cb.setSelected(true);
               cb.setLocation(5,i*20);
               cb.setSize(100,30);
               cb.setText(c.getBrand());
               jPanelBrand.add(cb);
               cb.setName(c.getBrand()+i);
               i++; 
               invalidate();
           }  
       }
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for(Car c : carCatalog.getCarCatalog())
        {
           if(brandArr.contains(c.getBrand()) && manufacturerArr.contains(c.getManufacturerName())){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = c;
            row[1] = c.getManufacturerName();
            row[2] = c.getYearOfManufacture();
            row[3] = c.getModelNumber();
            row[4] = c.getSerialNumber();
            row[5] = c.getColor();
            row[6] = c.getCity();
            row[7] = c.getNumberOfSeats();
            if(c.getMaintenanceCertificate().equals("expired")){
                row[8] = "Expired";
            }else if(c.getMaintenanceCertificate().equals("notexpired")){
                row[8] = "Not Expired";
            }
            row[9] = c.isAvailability();
            dtm.addRow(row);
           }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSearchCar = new javax.swing.JButton();
        jButtonSearchCarBrand = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelCarManufacturer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelBrand = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of Car Manufacturers");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Car Brand");

        jButtonSearchCar.setText("Search Car");
        jButtonSearchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCarActionPerformed(evt);
            }
        });

        jButtonSearchCarBrand.setText("Search Car Brand");
        jButtonSearchCarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCarBrandActionPerformed(evt);
            }
        });

        jButtonBack.setText("<<Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelCarManufacturer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelCarManufacturerLayout = new javax.swing.GroupLayout(jPanelCarManufacturer);
        jPanelCarManufacturer.setLayout(jPanelCarManufacturerLayout);
        jPanelCarManufacturerLayout.setHorizontalGroup(
            jPanelCarManufacturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanelCarManufacturerLayout.setVerticalGroup(
            jPanelCarManufacturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelCarManufacturer);

        jPanelBrand.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelBrandLayout = new javax.swing.GroupLayout(jPanelBrand);
        jPanelBrand.setLayout(jPanelBrandLayout);
        jPanelBrandLayout.setHorizontalGroup(
            jPanelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jPanelBrandLayout.setVerticalGroup(
            jPanelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanelBrand);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Manufacturer Name", "Year of Manufacturer", "Model Number", "Serial Number", "Color", "City", "Number of Seats", "Maintenance Certificate", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(164, 164, 164))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSearchCarBrand)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonBack)
                        .addGap(481, 481, 481)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonSearchCar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSearchCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSearchCar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.jPanelBottom.remove(this);
        CardLayout layout = (CardLayout)this.jPanelBottom.getLayout();
        layout.previous(jPanelBottom);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSearchCarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCarBrandActionPerformed
        // TODO add your handling code here:
        jPanelBrand.removeAll();
        manufacturerArr.clear();
        jPanelBrand.updateUI();
        brandArr.clear();
        Component[] carManufacturerComponents = jPanelCarManufacturer.getComponents();
        for (Component c : carManufacturerComponents) {
            if(c instanceof JCheckBox){
              JCheckBox cb = (JCheckBox)c;
              if (cb.isSelected()){
                  manufacturerArr.add(cb.getText());
              }  
            }
        }
        populateCarBrand();
        
    }//GEN-LAST:event_jButtonSearchCarBrandActionPerformed

    private void jButtonSearchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCarActionPerformed
        // TODO add your handling code here:
        manufacturerArr.clear();
        brandArr.clear();
        
        Component[] carManufacturerComponents = jPanelCarManufacturer.getComponents();
        for (Component c : carManufacturerComponents) {
            if(c instanceof JCheckBox){
              JCheckBox cb = (JCheckBox)c;
              if (cb.isSelected()){
                  manufacturerArr.add(cb.getText());
              }  
            }
        }
        
        Component[] brandComponents = jPanelBrand.getComponents();
        for (Component c : brandComponents) {
            if(c instanceof JCheckBox){
              JCheckBox cb = (JCheckBox)c;
              if (cb.isSelected()){
                  brandArr.add(cb.getText());
              }  
            }
        }
        populateTable();
    }//GEN-LAST:event_jButtonSearchCarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSearchCar;
    private javax.swing.JButton jButtonSearchCarBrand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBrand;
    private javax.swing.JPanel jPanelCarManufacturer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
