/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dedhi
 */
public class ManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageJPanel
     */
    private JPanel jPanelBottom;
    private CarCatalog carCatalog;
    public ManageJPanel(JPanel jPanelBottom, CarCatalog carCatalog) {
        initComponents();
        this.jPanelBottom = jPanelBottom;
        this.carCatalog = carCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCarManuList = new javax.swing.JButton();
        jButtonFirstCar = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonFilterCars = new javax.swing.JButton();

        jButtonCarManuList.setText("Filter by Car Manufacturers");
        jButtonCarManuList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarManuListActionPerformed(evt);
            }
        });

        jButtonFirstCar.setText("View first available Car");
        jButtonFirstCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstCarActionPerformed(evt);
            }
        });

        jButtonBack.setText("<<Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonFilterCars.setText("Filter Cars");
        jButtonFilterCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterCarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButtonFirstCar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonFilterCars, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonCarManuList, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonBack)))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonBack)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFirstCar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarManuList, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilterCars, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(535, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCarManuListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarManuListActionPerformed
        // TODO add your handling code here:
        //Addition of CarManufacturerJPanel to the card layout on button OnClick and displaying he panel
        CarManufacturerJPanel carManufacturerJPanel = new CarManufacturerJPanel(jPanelBottom, carCatalog);
        jPanelBottom.add("CarManufacturerJPanel",carManufacturerJPanel);
        CardLayout layout = (CardLayout) jPanelBottom.getLayout();
        layout.next(jPanelBottom);
    }//GEN-LAST:event_jButtonCarManuListActionPerformed

    private void jButtonFirstCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstCarActionPerformed
        // TODO add your handling code here:
        //Calling getFirstCar() method of car Catalog to get the first car object
        Car car = carCatalog.getFirstCar();
        //Displying the car object using ViewJPanel
        ViewJPanel viewJPanel = new ViewJPanel(jPanelBottom, carCatalog, car);
        viewJPanel.disableBtnUpdate();
        jPanelBottom.add("ViewJPanel",viewJPanel);
        CardLayout layout = (CardLayout) jPanelBottom.getLayout();
        layout.next(jPanelBottom);
    }//GEN-LAST:event_jButtonFirstCarActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        //Code for back button
        //Removing the current panel and displaying the previous one
        this.jPanelBottom.remove(this);
        CardLayout layout = (CardLayout)this.jPanelBottom.getLayout();
        layout.previous(jPanelBottom);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonFilterCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterCarsActionPerformed
        // TODO add your handling code here:
        //Addition of SearchCar in Card layout on Button OnClick and displaying the panel
        SearchCar searchCar = new SearchCar(jPanelBottom, carCatalog);
        jPanelBottom.add("SearchCar", searchCar);
        CardLayout layout = (CardLayout) jPanelBottom.getLayout();
        layout.next(jPanelBottom);
    }//GEN-LAST:event_jButtonFilterCarsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCarManuList;
    private javax.swing.JButton jButtonFilterCars;
    private javax.swing.JButton jButtonFirstCar;
    // End of variables declaration//GEN-END:variables
}
