/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dedhi
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel jPanelBottom;
    private CarCatalog carCatalog;
    private Car car;
    public ViewJPanel(JPanel jPanelBottom, CarCatalog carCatalog, Car car) {
        initComponents();
        this.jPanelBottom = jPanelBottom;
        this.carCatalog = carCatalog;
        this.car = car;
        
        //Displaying all the attributes of car object
        jTxtBrand.setText(car.getBrand());
        jTxtManufacturerName.setText(car.getManufacturerName());
        jTxtModelNum.setText(String.valueOf(car.getModelNumber()));
        jTxtSerialNum.setText(String.valueOf(car.getSerialNumber()));
        jTxtYearOfManufacture.setText(String.valueOf(car.getYearOfManufacture()));
        jComboBoxCity.setSelectedItem(car.getCity());
        jTxtNoOfSeats.setText(String.valueOf(car.getNumberOfSeats()));
        jTxtColor.setText(car.getColor());
        if(car.getMaintenanceCertificate().equals("expired")){
            jRadioButtonExpired.setSelected(true);
        } else if(car.getMaintenanceCertificate().equals("notexpired")){
            jRadioButtonNotExpired.setSelected(true);
        }
        jTxtDriverName.setText(car.getDriverName());
        if(car.isAvailability()==true){
            jRadioButtonAvailYes.setSelected(true);
        }else if(car.isAvailability() == false){
            jRadioButtonAvailNo.setSelected(true);
        }
        
        jBtnUpdate.setEnabled(true);
        jBtnSave.setEnabled(false);
    }
    
    public void disableBtnUpdate(){
        jBtnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMainCerti = new javax.swing.ButtonGroup();
        buttonGroupAvail = new javax.swing.ButtonGroup();
        jLblCity = new javax.swing.JLabel();
        jComboBoxCity = new javax.swing.JComboBox<>();
        jLblNoOfSeats = new javax.swing.JLabel();
        jTxtNoOfSeats = new javax.swing.JTextField();
        jLblColor = new javax.swing.JLabel();
        jTxtColor = new javax.swing.JTextField();
        jRadioButtonNotExpired = new javax.swing.JRadioButton();
        jRadioButtonExpired = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLblDriverName = new javax.swing.JLabel();
        jTxtDriverName = new javax.swing.JTextField();
        jLblAvailability = new javax.swing.JLabel();
        jRadioButtonAvailYes = new javax.swing.JRadioButton();
        jLblTitle = new javax.swing.JLabel();
        jRadioButtonAvailNo = new javax.swing.JRadioButton();
        jLblManufacturerName = new javax.swing.JLabel();
        jBtnUpdate = new javax.swing.JButton();
        jTxtManufacturerName = new javax.swing.JTextField();
        jLblBrand = new javax.swing.JLabel();
        jLblModelNum = new javax.swing.JLabel();
        jTxtModelNum = new javax.swing.JTextField();
        jTxtBrand = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jTxtSerialNum = new javax.swing.JTextField();
        jLblManufacturerName2 = new javax.swing.JLabel();
        jTxtYearOfManufacture = new javax.swing.JTextField();
        jLblYearOfManufacture = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();

        jLblCity.setText("City");

        jComboBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "Cambridge", "Quincy", "Framingham", "Somerville" }));
        jComboBoxCity.setEnabled(false);

        jLblNoOfSeats.setText("Number of Seats");

        jTxtNoOfSeats.setEnabled(false);

        jLblColor.setText("Color");

        jTxtColor.setEnabled(false);

        buttonGroupMainCerti.add(jRadioButtonNotExpired);
        jRadioButtonNotExpired.setText("Not Expired");
        jRadioButtonNotExpired.setEnabled(false);

        buttonGroupMainCerti.add(jRadioButtonExpired);
        jRadioButtonExpired.setText("Expired");
        jRadioButtonExpired.setEnabled(false);

        jLabel1.setText("Maintenance Certificate");

        jLblDriverName.setText("Driver Name");

        jTxtDriverName.setEnabled(false);

        jLblAvailability.setText("Is your car currently available?");

        buttonGroupAvail.add(jRadioButtonAvailYes);
        jRadioButtonAvailYes.setText("Yes");
        jRadioButtonAvailYes.setEnabled(false);

        jLblTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitle.setText("View Car");

        buttonGroupAvail.add(jRadioButtonAvailNo);
        jRadioButtonAvailNo.setText("No");
        jRadioButtonAvailNo.setEnabled(false);

        jLblManufacturerName.setText("Manufacturer Name");

        jBtnUpdate.setText("UPDATE");
        jBtnUpdate.setEnabled(false);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jTxtManufacturerName.setEnabled(false);

        jLblBrand.setText("Brand");

        jLblModelNum.setText("Model Number");

        jTxtModelNum.setEnabled(false);

        jTxtBrand.setEnabled(false);

        jButtonBack.setText("<<Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jTxtSerialNum.setEnabled(false);

        jLblManufacturerName2.setText("Serial Number");

        jTxtYearOfManufacture.setEnabled(false);

        jLblYearOfManufacture.setText("Year of Manufacture");

        jBtnSave.setText("SAVE");
        jBtnSave.setEnabled(false);
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)
                        .addGap(254, 254, 254)
                        .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLblDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jTxtDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLblManufacturerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblManufacturerName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblModelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblYearOfManufacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblNoOfSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtNoOfSeats)
                                    .addComponent(jTxtYearOfManufacture)
                                    .addComponent(jTxtSerialNum)
                                    .addComponent(jTxtModelNum)
                                    .addComponent(jTxtManufacturerName)
                                    .addComponent(jTxtBrand)
                                    .addComponent(jTxtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNotExpired)
                                .addGap(29, 29, 29)
                                .addComponent(jRadioButtonExpired))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLblAvailability)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jRadioButtonAvailYes)
                                .addGap(27, 27, 27)
                                .addComponent(jRadioButtonAvailNo)))))
                .addContainerGap(583, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblManufacturerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtColor)
                    .addComponent(jLblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonNotExpired)
                        .addComponent(jRadioButtonExpired))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDriverName)
                    .addComponent(jTxtDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAvailYes)
                    .addComponent(jRadioButtonAvailNo)
                    .addComponent(jLblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUpdate)
                    .addComponent(jBtnSave))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        // TODO add your handling code here:
        jBtnUpdate.setEnabled(false);
        jBtnSave.setEnabled(true);
        
        jTxtBrand.setEnabled(true);
        jTxtManufacturerName.setEnabled(true);
        jTxtModelNum.setEnabled(true);
        jTxtSerialNum.setEnabled(true);
        jTxtYearOfManufacture.setEnabled(true);
        jComboBoxCity.setEnabled(true);
        jTxtNoOfSeats.setEnabled(true);
        jTxtColor.setEnabled(true);
        jRadioButtonExpired.setEnabled(true);
        jRadioButtonNotExpired.setEnabled(true);
        jTxtDriverName.setEnabled(true);
        jRadioButtonAvailYes.setEnabled(true);
        jRadioButtonAvailNo.setEnabled(true);
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        //On backbutton refreshing the table as er changes made by the user
        this.jPanelBottom.remove(this);
        CardLayout layout = (CardLayout)this.jPanelBottom.getLayout();
        
        Component[] comps = this.jPanelBottom.getComponents();
        for(Component comp :  comps){
            System.out.println(comp);
            if(comp instanceof SearchCar){
                SearchCar searchCar = (SearchCar) comp;
                searchCar.populateTable();
                //searchCar.setJLabelLastUpdate();
            }
            
        }     
        layout.previous(jPanelBottom);
    }//GEN-LAST:event_jButtonBackActionPerformed

    //Saving the changes made by user by updating the car object attributes
    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
        //Validating the data entered by user
        String brand = jTxtBrand.getText();
        if(brand==null || brand.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a valid Brand Name!");
            return;
        }
        String manufacturerName = jTxtManufacturerName.getText();
        if(manufacturerName==null || manufacturerName.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a valid Manufacturer Name!");
            return;
        }
        try{
            Integer.parseInt(jTxtModelNum.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid Model Number!");
            return;
        }

        try{
            Integer.parseInt(jTxtSerialNum.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid Serial Number!");
            return;
        }

        try{
            Integer.parseInt(jTxtYearOfManufacture.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid Year!");
            return;
        }

        String city = jComboBoxCity.getSelectedItem().toString();

        try{
            Integer.parseInt(jTxtNoOfSeats.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a valid Number of Seats!");
            return;
        }

        String color = jTxtColor.getText();
        if(color==null || color.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a valid Color!");
            return;
        }
        String maintenanceCertificate;
        if(jRadioButtonNotExpired.isSelected()){
            maintenanceCertificate = "notexpired";
        }else if(jRadioButtonExpired.isSelected()){
            maintenanceCertificate = "expired";
        }else{
            JOptionPane.showMessageDialog(null, "Please select a value!");
            return;
        }
        String driverName = jTxtDriverName.getText();
        if(driverName==null || driverName.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a valid Driver Name!");
            return;
        }
        boolean availability = false;
        if(jRadioButtonAvailYes.isSelected()){
            availability = true;
        }else if(jRadioButtonAvailNo.isSelected()){
            availability = false;
        }else{
            JOptionPane.showMessageDialog(null, "Please select a value!");
            return;
        }
        
        //Updating the attributes of car object selected by the user
        car.setBrand(brand);
        car.setManufacturerName(manufacturerName);
        car.setModelNumber(Integer.parseInt(jTxtModelNum.getText()));
        car.setSerialNumber(Integer.parseInt(jTxtSerialNum.getText()));
        car.setYearOfManufacture(Integer.parseInt(jTxtYearOfManufacture.getText()));
        car.setCity(city);
        car.setNumberOfSeats(Integer.parseInt(jTxtNoOfSeats.getText()));
        car.setColor(color);
        car.setMaintenanceCertificate(maintenanceCertificate);
        car.setDriverName(driverName);
        car.setAvailability(availability);

        //Showing success message
        JOptionPane.showMessageDialog(null, "Car updated successfully!","information",JOptionPane.INFORMATION_MESSAGE);
        //Since data was updated updating the date attribute
        Calendar now = Calendar.getInstance(); 
        CarCatalog.setLastUpdate(now.getTime());
        
        jBtnUpdate.setEnabled(true);
        jBtnSave.setEnabled(false);
        
        //Disabling the text fields after saving the data
        jTxtBrand.setEnabled(false);
        jTxtManufacturerName.setEnabled(false);
        jTxtModelNum.setEnabled(false);
        jTxtSerialNum.setEnabled(false);
        jTxtYearOfManufacture.setEnabled(false);
        jComboBoxCity.setEnabled(false);
        jTxtNoOfSeats.setEnabled(false);
        jTxtColor.setEnabled(false);
        jRadioButtonExpired.setEnabled(false);
        jRadioButtonNotExpired.setEnabled(false);
        jTxtDriverName.setEnabled(false);
        jRadioButtonAvailYes.setEnabled(false);
        jRadioButtonAvailNo.setEnabled(false);
    }//GEN-LAST:event_jBtnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAvail;
    private javax.swing.ButtonGroup buttonGroupMainCerti;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JComboBox<String> jComboBoxCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAvailability;
    private javax.swing.JLabel jLblBrand;
    private javax.swing.JLabel jLblCity;
    private javax.swing.JLabel jLblColor;
    private javax.swing.JLabel jLblDriverName;
    private javax.swing.JLabel jLblManufacturerName;
    private javax.swing.JLabel jLblManufacturerName2;
    private javax.swing.JLabel jLblModelNum;
    private javax.swing.JLabel jLblNoOfSeats;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JLabel jLblYearOfManufacture;
    private javax.swing.JRadioButton jRadioButtonAvailNo;
    private javax.swing.JRadioButton jRadioButtonAvailYes;
    private javax.swing.JRadioButton jRadioButtonExpired;
    private javax.swing.JRadioButton jRadioButtonNotExpired;
    private javax.swing.JTextField jTxtBrand;
    private javax.swing.JTextField jTxtColor;
    private javax.swing.JTextField jTxtDriverName;
    private javax.swing.JTextField jTxtManufacturerName;
    private javax.swing.JTextField jTxtModelNum;
    private javax.swing.JTextField jTxtNoOfSeats;
    private javax.swing.JTextField jTxtSerialNum;
    private javax.swing.JTextField jTxtYearOfManufacture;
    // End of variables declaration//GEN-END:variables
}
