/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSign;
import Business.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dedhi
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private VitalSignHistory vsh;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;
        populateTable();
    }
    
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) jVitalSignTable.getModel();
        dtm.setRowCount(0);
        
        for(VitalSign vs: vsh.getVitalSignHistory())
        {
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getBloodPressure();
            dtm.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jVitalSignTable = new javax.swing.JTable();
        jViewDetailsBtn = new javax.swing.JButton();
        jDeleteVitalSignBtn = new javax.swing.JButton();
        jPulseLabel = new javax.swing.JLabel();
        jDateLabel = new javax.swing.JLabel();
        jTemperatureTextField = new javax.swing.JTextField();
        jBloodPressureTextField = new javax.swing.JTextField();
        jPulseTextField = new javax.swing.JTextField();
        jDateTextField = new javax.swing.JTextField();
        jTemperatureLabel = new javax.swing.JLabel();
        jBloodPressureLabel = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("View Vital Signs");

        jVitalSignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jVitalSignTable);

        jViewDetailsBtn.setText("View Details");
        jViewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewDetailsBtnActionPerformed(evt);
            }
        });

        jDeleteVitalSignBtn.setText("Delete");
        jDeleteVitalSignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteVitalSignBtnActionPerformed(evt);
            }
        });

        jPulseLabel.setText("Date:");

        jDateLabel.setText("Pulse:");

        jTemperatureTextField.setEnabled(false);

        jBloodPressureTextField.setEnabled(false);

        jPulseTextField.setEnabled(false);

        jDateTextField.setEnabled(false);

        jTemperatureLabel.setText("Temperature:");

        jBloodPressureLabel.setText("Blood Pressure:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jViewDetailsBtn)
                                .addGap(58, 58, 58)
                                .addComponent(jDeleteVitalSignBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTemperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPulseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBloodPressureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTemperatureTextField)
                                    .addComponent(jBloodPressureTextField)
                                    .addComponent(jPulseTextField)
                                    .addComponent(jDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTemperatureLabel)
                            .addComponent(jTemperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBloodPressureLabel)
                            .addComponent(jBloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateLabel)
                            .addComponent(jPulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPulseLabel)
                            .addComponent(jDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnConfirm))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeleteVitalSignBtn)
                    .addComponent(jViewDetailsBtn))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jViewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRows = jVitalSignTable.getSelectedRow();
        
        if(selectedRows >=0){
            VitalSign vs = (VitalSign) jVitalSignTable.getValueAt(selectedRows, 0);
            jTemperatureTextField.setText(String.valueOf(vs.getTemperature()));
            jBloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
            jPulseTextField.setText(String.valueOf(vs.getPulse()));
            jDateTextField.setText(vs.getDate());
        } else{
            JOptionPane.showMessageDialog(null, "Please select a Vital Sign");
        }
    }//GEN-LAST:event_jViewDetailsBtnActionPerformed

    private void jDeleteVitalSignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteVitalSignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRows = jVitalSignTable.getSelectedRow();
        
        if(selectedRows >=0){
            VitalSign vs = (VitalSign) jVitalSignTable.getValueAt(selectedRows, 0);
            vsh.deleteVitalSign(vs);
            populateTable();
            JOptionPane.showMessageDialog(null, "Vital Sign Deleted successfully");
        } else{
            JOptionPane.showMessageDialog(null, "Please select a Vital Sign");
        }
    }//GEN-LAST:event_jDeleteVitalSignBtnActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        jTemperatureTextField.setEnabled(true);
        jBloodPressureTextField.setEnabled(true);
        jPulseTextField.setEnabled(true);
        jDateTextField.setEnabled(true);
        
        btnUpdate.setEnabled(false);
        btnConfirm.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        int selectedRow = jVitalSignTable.getSelectedRow();
        
        if(selectedRow >= 0){
            VitalSign vs = (VitalSign) jVitalSignTable.getValueAt(selectedRow, 0);
            vs.setTemperature(Double.parseDouble(jTemperatureTextField.getText()));
            vs.setBloodPressure(Double.parseDouble(jBloodPressureTextField.getText()));
            vs.setPulse(Integer.parseInt(jPulseTextField.getText()));
            vs.setDate(jDateTextField.getText());
            
            populateTable();
            
            btnUpdate.setEnabled(true);
            btnConfirm.setEnabled(false);
            
            jTemperatureTextField.setEnabled(false);
            jBloodPressureTextField.setEnabled(false);
            jPulseTextField.setEnabled(false);
            jDateTextField.setEnabled(false);
            
            JOptionPane.showMessageDialog(null, "Vital Sign updated successfully");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jBloodPressureLabel;
    private javax.swing.JTextField jBloodPressureTextField;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JTextField jDateTextField;
    private javax.swing.JButton jDeleteVitalSignBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jPulseLabel;
    private javax.swing.JTextField jPulseTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTemperatureLabel;
    private javax.swing.JTextField jTemperatureTextField;
    private javax.swing.JButton jViewDetailsBtn;
    private javax.swing.JTable jVitalSignTable;
    // End of variables declaration//GEN-END:variables
}
